Player.create(name:"Jonjo Shelvey", age: 28, position:"Mid")
Player.create(name:"Joelinton", age: 23, position:"Fwd")
Player.create(name:"Jamaal Lascelles", age: 26, position:"Def")
Player.create(name:"Fabian Schar", age: 28, position:"Def")
Player.create(name:"Martin Dubravka", age: 31, position:"GK")
Player.create(name:"Bruno Fernandes", age: 25, position:"Mid")
Player.create(name:"Odion Ighalo", age: 30, position:"Fwd")
Player.create(name:"Aaron Wan-Bissaka", age: 22, position:"Def")
Player.create(name:"David De Gea", age: 29, position:"GK")
Player.create(name:"Harry Kane", age: 26, position:"Fwd")
Player.create(name:"Heung-Min Son", age: 27, position:"Mid")
Player.create(name:"Toby Alderwiereld", age: 31, position:"Def")
Player.create(name:"Hugo Lloris", age: 33, position:"GK")
Player.create(name:"Robert Lewandowski", age: 31, position:"Fwd")
Player.create(name:"Corentin Tolisso", age: 25, position:"Mid")
Player.create(name:"Alphonso Davies", age: 19, position:"Def")
Player.create(name: "Manuel Neuer", age: 34, position:"GK")
Player.create(name:"Rodrigo Moreno", age: 29, position:"Fwd")
Player.create(name:"Goncalo Guedes", age: 23, position:"Mid")
Player.create(name:"Alessandro Florenzi", age: 29, position:"Def")
Player.create(name: "Jasper Cillessen", age: 31, position:"GK")

